### PR TITLE
Add JAR file instructions

### LINKED ISSUE #254: Add JAR file instructions

### PR DESCRIPTION
**Pull request by nmalaguti**
Closes #254

### CODE REVIEW

**Comment by truell20** [comment]
Not sure if quickstart is the right place for this

**Comment by nmalaguti** [comment]
I wasn't sure what the best place was either. It seemed like the only page that mentioned submitting a zip file, so I figured it was the most relevant place.

I'm happy to move it somewhere else. What do you think?

**Comment by truell20** [comment]
Not totally sure, but think this might warrant a new guide. One that includes all of the possible things that you can include when updating a new bot (`install.sh`, a jar file, we are also considering allowing users to self report their bot's language by including a `LANGUAGE` file).

**Comment by nmalaguti** [comment]
It might be easier to write in a collaborative editor. Do you want to start a Google Doc or something so we can iterate on it?

**Comment by truell20** [comment]
A bit busy right now.

**Pull request closed without merging**
